### ISSUE TITLE
I wonder if the weight of this job is open source now

### ISSUE THREAD

**Issue by zengdashi** [tyang816/SES-Adapter#1]
This work is very much of interest to structural biology labs, and we would like to try to use this program for training on some specific protein species. So I'm curious if the protein language model weights mentioned in this work are already open source.
Looking forward to your reply very much!

**Comment by tyang816** [comment]
All the language models are open-source, you can find them in [huggingface](https://huggingface.co/).
Maybe the `ckpt/$plm_model` in my script makes you confused, I will change it, like `facebook/esm2_t33_650M_UR50D`.
Thanks for your feedback!

**Comment by zengdashi** [comment]
Thank you very much for your reply!
After re-reading the article and the code, I think I probably got it. Thanks again for your contribution to the scientific endeavor! I will close this issue.
